name: Android APK Build

on:
  push:
    branches:
      - DEV

  pull_request:
    branches:
      - DEV

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/RecipeShare.keystore
          test -s android/app/RecipeShare.keystore || (echo "ANDROID_KEYSTORE secret is missing or invalid" && exit 1)

      - name: Give Gradle Permission
        run: chmod +x android/gradlew

      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Generate APK Name
        run: |
          echo "APK_DATE=$(date +'%d%B%Y')" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk \
             android/app/build/outputs/apk/release/RecipeShare-${{ env.APK_DATE }}.apk
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RecipeShare-${{ env.APK_DATE }}
          path: Frontend/android/app/build/outputs/apk/release/RecipeShare-${{ env.APK_DATE }}.apk

      - name: Send APK Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: RecipeShare APK
          to: vikasjamkar2001@gmail.com
          from: GitHub Actions
          body: |
            Please find the latest APK attached.
          # attachments: Frontend/android/app/build/outputs/apk/release/app-release.apk